pacstall/pacstall-programs

- packages/pacget/pacget.pacscript
> pacget fix and half version bump

- packages/awesome-git/awesome-git.pacscript
This adds the new automatic version updates to the `-git` pacscripts I maintain.
> Add automatic updates

- packages/emacs/emacs.pacscript
> [Update] Port all options from `PKGBUILD` to `emacs.pacscript`

- packages/emacs-git/emacs-git.pacscript
- packages/emacs/emacs.pacscript
> [Update] Fix multicore compiling on `emacs-git.pacscript`

- packages/hyperfine-bin/hyperfine-bin.pacscript
> [Add Package] Add `hyperfine-bin`

- packages/awesome-git/awesome-git.pacscript
- packages/bemenu-git/bemenu-git.pacscript
- packages/emacs-git/emacs-git.pacscript
- packages/emacs/emacs.pacscript
- packages/hyperfine-bin/hyperfine-bin.pacscript
- packages/i3-gaps/i3-gaps.pacscript
- packages/uwufetch/uwufetch.pacscript
This addresses my pacscripts affected my #36.
Also, it updates the style of my pacscripts.
> [Update Package] Add licenses and style changes

- packages/bpytop-git/bpytop-git.pacscript
I made some modifications to the script, the license and the documentation will be installed with the program and some changes in the "style".
> [Update Package] bpytop-git

- packages/pipewire/pipewire.pacscript
This pull request updates Pipewire to the latest version at this time ([0.3.31](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.31)).
> [Update Package] PipeWire 0.3.31

- .github/workflows/test-package-install.yml
Fixes https://github.com/pacstall/pacstall-programs/issues/89
> Fix(CI): remove package

- packages/opensnitch-deb/opensnitch-deb.pacscript
- packages/opensnitch-ui-deb/opensnitch-ui-deb.pacscript
- packages/smartgit/smartgit.pacscript
- packages/yabridge/yabridge.pacscript
> Change maintainer email

- .github/workflows/sync-repo.yml
- packages/cutefish-calculator/cutefish-calculator.pacscript
- packages/cutefish-core/cutefish-core.pacscript
- packages/cutefish-dock/cutefish-dock.pacscript
- packages/cutefish-filemanager/cutefish-filemanager.pacscript
- packages/cutefish-icons/cutefish-icons.pacscript
- packages/cutefish-kwin-plugins/cutefish-kwin-plugins.pacscript
- packages/cutefish-launcher/cutefish-launcher.pacscript
- packages/cutefish-qt-plugins/cutefish-qt-plugins.pacscript
- packages/cutefish-settings/cutefish-settings.pacscript
- packages/cutefish-statusbar/cutefish-statusbar.pacscript
- packages/cutefish-wallpapers/cutefish-wallpapers.pacscript
- packages/fishui/fishui.pacscript
- packages/libcutefish/libcutefish.pacscript
Reverts pacstall/pacstall-programs#150
> Revert "Revert "[Draft] Add cutefish""

- packages/mailspring-deb/mailspring-deb.pacscript
- packages/tenacity-git/tenacity-git.pacscript
> Change my maintainer email [1.6 branch]

- packages/opensnitch-deb/opensnitch-deb.pacscript
postinst and removescript unnecessary
> The .deb already installs with pip

- packagelist
- packages/youtube-dl-git/README.md
- packages/youtube-dl-git/youtube-dl-git.pacscript
https://github.com/ytdl-org/youtube-dl git package.
> Add youtube-dl-git

- packagelist
- packages/grive2/grive2.pacscript
Add grive2 packate - https://github.com/vitalif/grive2
> Add grive2

- packagelist
- packages/fblog-deb/fblog-deb.pacscript
> Add fblog-deb

- packagelist
- packages/dbeaver-ce-deb/dbeaver-ce-deb.pacscript
> Add dbeaver-ce-deb

- packagelist
- packages/duf-deb/duf-deb.pacscript
> Add duf-deb

- packagelist
- packages/git-delta-deb/README.md
- packages/git-delta-deb/git-delta-deb.pacscript
> Add git-delta-deb

- packagelist
- packages/balena-etcher-electron-deb/README.md
- packages/balena-etcher-electron-deb/balena-etcher-electron-deb.pacscript
Add balena-etcher-electron-deb
> Add balena-etcher-electron-deb

- packagelist
- packages/aws-cli-v2-bin/README.md
- packages/aws-cli-v2-bin/aws-cli-v2-bin.pacscript
> Add aws-cli-v2-bin

- packagelist
- packages/telegram-bin/telegram-bin.pacscript
> PacReq: Add `telegram-bin`

- packagelist
- packages/microsoft-edge-dev-deb/microsoft-edge-dev-deb.pacscript
> [PacReq] [Package Add] Microsoft Edge Dev (Deb)

- packagelist
- packages/caprine-deb/caprine-deb.pacscript
> PacReq: `caprine-deb`

- packagelist
- packages/latte-dock-git/latte-dock-git.pacscript
> PacReq: Add `latte-dock-git`

- packagelist
Sort's `packagelist` in alphabetical order
> fix(packagelist): Sort in alphabetical order

- packages/moka-icon-theme/moka-icon-theme.pacscript
Hello!
It's about time I contributed a new package..
Tested on Ubuntu VM, as usual
> Add moka-icon-theme

- packages/telegram-bin/telegram-bin.pacscript
Updates `telegram-bin` to the latest release.
> upd(telegram-bin): `3.0.1` -> `3.1.0`

- packages/discord/discord.pacscript
I forgot to press propose changes 2 hours before whoops!
> Update Discord version and hash

- packages/telegram-bin/telegram-bin.pacscript
> upd(telegram-bin): `3.1.0` -> `3.1.1`

- packages/brave-browser-deb/brave-browser-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.30.86
> [Update Package] Brave Browser v1.30.86

- packages/brave-browser-deb/brave-browser-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.30.87
> [Update Package] Brave Browser v1.30.87

- packagelist
- packages/i3lock-color/i3lock-color.pacscript
This PR Adds `i3lock-color` to the repo
> Add i3lock-color

- packages/brave-browser-deb/brave-browser-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.31.88
> [Update Package] Brave Browser v1.31.88

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.32.85
> [Update Package] Brave Browser Dev v1.32.85

- packagelist
- packages/opera-beta-deb/opera-beta-deb.pacscript
https://blogs.opera.com/desktop/2021/10/opera-81-0-4196-27-beta-update/
> [Package Add] Opera Beta (Deb)

- packages/brave-browser-deb/brave-browser-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.31.91
> [Update Package] Brave Browser v1.31.91

- packages/ivpn-ui-deb/ivpn-ui-deb.pacscript
https://repo.ivpn.net/stable/pool/ivpn-ui_3.4.0_amd64.deb
> [Update Package] IVPN UI v3.4.0

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.32.96
> [Update Package] Brave Browser Dev v1.32.96

- packages/ardour-git/ardour-git.pacscript
> Ardour-git resolve double master

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.33.76
> [Update Package] Brave Browser Dev v1.33.76

- packages/brave-browser-deb/brave-browser-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.32.106
https://bin.snopyta.org/?73bba81ae31573d8#4mZv4r74Kc5Z212j1ZZE9gNDs4K2ZEgV92FyaSyeJ3t2
> [Update Package] Brave Browser v1.32.106

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.33.81
> [Update Package] Brave Browser Dev v1.33.81

- packagelist
- packages/httptoolkit-deb/httptoolkit-deb.pacscript
https://github.com/httptoolkit/httptoolkit-desktop
> [Package Add] HTTP Toolkit (Deb)

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.33.88
> [Update Package] Brave Browser Dev v1.33.88

- packagelist
- packages/spacecadetpinball-git/spacecadetpinball-git.pacscript
- packages/spacecadetpinball-git/spacecadetpinball.desktop
> feat(packagelist): Add `spacecadetpinball-git`

- packages/ivpn-ui-deb/ivpn-ui-deb.pacscript
https://repo.ivpn.net/stable/pool/ivpn-ui_3.4.5_amd64.deb
> [Update Package] IVPN UI v3.4.5

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.34.58
> upd(brave-browser-dev-deb): `1.33.88` -> `1.34.58`

- packagelist
- packages/treefetch-bin/treefetch-bin.pacscript
> add: `treefetch-bin`

- packagelist
- packages/tmpmail-bin/tmpmail-bin.pacscript
> add: `tmpmail-bin`

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.34.69
> upd(brave-browser-dev-deb): `1.34.58` -> `1.34.69`

- packagelist
- packages/pipes.sh-bin/pipes.sh-bin.pacscript
> add: `pipes.sh-bin`

- packagelist
- packages/qogir-icon-theme-bin/qogir-icon-theme-bin.pacscript
> add: `qogir-icon-theme-bin`

- packagelist
- packages/zentile-bin/zentile-bin.pacscript
> add: `zentile-bin`

- packagelist
- packages/doas-git/doas-git.pacscript
- packages/doas-git/doas-pam
- packages/doas-git/doas.conf
> add: `doas-git`

- packages/opera-deb/opera-deb.pacscript
https://download5.operacdn.com/pub/opera/desktop/82.0.4227.43/linux/opera-stable_82.0.4227.43_amd64.deb
> upd(opera-deb): `81.0.4196.54` -> `82.0.4227.43`

- packagelist
- packages/windscribe-legacy-cli-deb/windscribe-legacy-cli-deb.pacscript
See https://windscribe.com/guides/linux
> upd(windscribe): mark the old CLI as no longer maintained

- packagelist
- packages/endlessh-git/endlessh-git.pacscript
- packages/endlessh-git/sample-config
> add: `endlessh-git`

- packages/git-delta-deb/git-delta-deb.pacscript
git-delta-deb updated from 0.83 to 0.11.3.
And I removed myself from the maintainer.
> upd(git-delta-deb): `0.8.3` -> `0.11.3`

- packages/brave-browser-deb/brave-browser-deb.pacscript
See https://github.com/brave/brave-browser/releases/tag/v1.34.80
> upd(brave-browser-deb): `1.33.106` -> `1.34.80`

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
See https://github.com/brave/brave-browser/releases/tag/v1.35.76
> upd(brave-browser-dev-deb): `1.34.69` -> `1.35.76`

- packagelist
- packages/grive2-git/grive2-git.pacscript
- packages/librewolf-app/librewolf-app.pacscript
add grive2-git for grive2 latest version
> add: `grive2-git`

- packagelist
- packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
- packages/an-anime-game-launcher/an-anime-game-launcher.pacscript
Adds An Anime Game Launcher
[Source](https://gitlab.com/KRypt0n_/an-anime-game-launcher)
I am one of the devs of the project and since we already have an AUR package and got told about this project we thought it would be a nice idea to translate the AUR package over.
> add: `an-anime-game-launcher-bin`

- packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
> upd(an-anime-game-launcher-bin): 2.1.0 -> 2.1.1

- packagelist
- packages/plexmediaserver-deb/plexmediaserver-deb.pacscript
> add: `plexmediaserver-deb`

- README.md
- packagelist
- packages/shellcheck-bin/shellcheck-bin.pacscript
> add: `shellcheck-bin`

- packagelist
- packages/fennel/fennel.pacscript
> add: `fennel`

- packagelist
- packages/yafetch-git/yafetch-git.pacscript
> add: `yafetch-git`

- packages/brave-browser-dev-deb/brave-browser-dev-deb.pacscript
https://github.com/brave/brave-browser/releases/tag/v1.37.73
> upd(brave-browser-dev-deb): `1.36.91` -> `1.37.73`

- packagelist
- packages/chezmoi-deb/chezmoi-deb.pacscript
> add: `chezmoi-deb`

- packagelist
- packages/fnlfmt/fnlfmt.pacscript
> add: `fnlfmt`

- packagelist
- packages/reshade-shaders-git/reshade-shaders-git.pacscript
> add: `reshade-shaders-git`

- packagelist
- packages/bat-deb/bat-deb.pacscript
> add: `bat-deb`

- packagelist
- packages/lyx-common-deb/lyx-common-deb.pacscript
> add: `lyx-common-deb`

- packagelist
- packages/gomuks-deb/gomuks-deb.pacscript
> add: `gomuks-deb`

- packages/discord-canary/discord-canary.pacscript
Updated from `0.0.134` to `0.0.135` and add a repology variable.
> upd(discord-canary): `0.0.134` -> `0.0.135`

- packages/minecraft-launcher/minecraft-launcher.pacscript
This also fixes the desktop file since aranym's github user doesn't exist anymore.
> upd(minecraft-launcher): `921` -> `1121`

- packagelist
- packages/noisetorch-bin/noisetorch-bin.pacscript
> add: `noisetorch-bin`

- packagelist
- packages/protonvpn-cli/protonvpn-cli.pacscript
> add: `protonvpn-cli`

- packagelist
- packages/glow-deb/glow-deb.pacscript
> add: `glow-deb`

- packagelist
- packages/bottles/bottles.pacscript
Closes #576 
~~Currently has issues on stable and older releases of ubuntu and debian due to mismatched libhandy version.~~
EDIT: Issues are fixed now due to the latest LTS release of ubuntu.
> add: `bottles`

- packagelist
- packages/proton-python-client/proton-python-client.pacscript
> add: `proton-python-client`

- packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
I don’t know how to build the latest commit, so this is a temporary patch https://github.com/royshil/obs-backgroundremoval/issues/96
> fix(obs-backgroundremoval-git): build temporary fix

- packagelist
- packages/notion-app-enhanced-deb/notion-app-enhanced-deb.pacscript
> add: `notion-app-enhanced-deb`

- packages/librewolf-app/librewolf-app.pacscript
> fix(librewolf-app): update icon link

- packagelist
- packages/jonaburg-picom-git/jonaburg-picom-git.pacscript
- Adding `jonaburg-picom-git` to the list of supported packages.
- `jonaburg-picom-git.pacscript` has been added.
- The packagelist is also updated with `jonaburg-picom-git`.
I had a question, since picom has a config file, where do I put it, since it needs to be stowed. Please suggest.
Thanks
> add: `jonaburg-picom-git`

- packagelist
- packages/ibhagwan-picom-git/ibhagwan-picom-git.pacscript
- Adding `ibhagwan-picom-git` to the list of supported packages.
- `ibhagwan-picom-git.pacscript` has been added.
- The `packagelist` is also updated with `ibhagwan-picom-git`.
> add: `ibhagwan-picom-git`

- packages/qtile-git/qtile-git.pacscript
- Fixed installation error (unable to verify version from `pyproject.toml`) for `qtile-git`.
- Updated dependencies.
> upd(qtile-git): fix installation error

- packagelist
- packages/atom-editor-deb/atom-editor-deb.pacscript
https://github.blog/2022-06-08-sunsetting-atom/
> rm: `atom-editor-deb`

- packagelist
- packages/windscribe-legacy-cli-deb/windscribe-legacy-cli-deb.pacscript
v2.0 has a command line interface
https://blog.windscribe.com/desktop-app-2-0-903fce58225a/
> rm: `windscribe-legacy-cli-deb`

- packages/discord/discord.pacscript
Here we go again...
locally sha256summed and edited with web editor please lmk if I forgot something
> upd(discord): `0.0.17` -> `0.0.18`

- packages/plexmediaserver-deb/plexmediaserver-deb.pacscript
> upd(plexmediaserver-deb): `1.26.2.5797-5bd057d2b` -> `1.27.1.5916-6b0e31a64`

- packages/telegram-bin/telegram-bin.pacscript
> upd(telegram-bin): `3.7.3` -> `4.0.1`

- packagelist
- packages/ferium-bin/ferium-bin.pacscript
https://github.com/gorilla-devs/ferium/issues/42
> add: `ferium-bin`

- packagelist
- packages/postman-bin/postman-bin.pacscript
> add: `postman-bin`

- packages/ferium-bin/ferium-bin.pacscript
Update Ferium from version `4.1.7` to `4.1.8`
> upd(ferium-bin): `4.1.7` -> `4.1.8`

- packagelist
- packages/chwp-deb/chwp-deb.pacscript
Link to repo: https://github.com/RouHim/chwp
> Changes the wallpaper from the command line.
> add: `chwp-deb`

- packages/discord-deb/discord-deb.pacscript
- packages/discord/discord.pacscript
not sure how to format dual updates
I'd like to avoid opening two branches on my fork though. 
deb has been tested myself, not sure about the other one, I just wget them and the run sha256sum
> upd(discord/discord-deb): `0.0.18` -> `0.0.19`

- packagelist
- packages/nerd-fonts-jetbrains-mono/nerd-fonts-jetbrains-mono.pacscript
Same layout as `nerd-fonts-hack`, just different font
> add: `nerd-fonts-jetbrains-mono`

- .github/workflows/tests.yml
This will let pacscripts that work on Ubuntu but not Debian and vice-versa complete the CI for the appropriate distro
> feat(CI): Seperate Debian and Ubuntu

- packages/bat-deb/bat-deb.pacscript
- packages/chezmoi-deb/chezmoi-deb.pacscript
- packages/glow-deb/glow-deb.pacscript
Unfortunately, I have switched to a non-Debian based distro so no longer use pacstall. Since I can no longer test packages, locally, I would like to remove myself as a maintainer.
> Remove mirenradia as maintainer

- packages/discord-canary/discord-canary.pacscript
> upd(discord-canary): `0.0.138` -> `0.0.139`

- packages/discord-deb/discord-deb.pacscript
- packages/discord/discord.pacscript
> upd(discord/discord-deb): `0.0.19` -> `0.0.20`

- packages/vscode-deb/vscode-deb.pacscript
> upd(vscode-deb): `1.70.2` -> `1.71.2`

- packagelist
there is no package named waf-git
> fix(waf): change waf-git back to waf in packagelist

- packagelist
- packages/windscribe-alpha-gui-deb/windscribe-alpha-gui-deb.pacscript
> add: `windscribe-alpha-gui-deb`

- packagelist
- packages/surfshark-vpn-cli-deb/surfshark-vpn-cli-deb.pacscript
> rm: `surfshark-vpn-cli-deb`

- packagelist
- packages/surfshark-gui-deb/surfshark-gui-deb.pacscript
> add: `surfshark-gui-deb`

- packages/micro/micro.pacscript
Closes https://github.com/pacstall/pacstall-programs/pull/1680
> upd(micro): `2.0.10` -> `2.0.11`

- packages/kalendar-git/kalendar-git.pacscript
Compiles fine in Kubuntu 22.10 (will not work in versions < 22.10 nor debian)
> fix(kalendar-git): fix build with pacstall 3 and Ubuntu 22.10

- packagelist
- packages/touchegg-git/touchegg-git.pacscript
> add: `touchegg-git`

- packagelist
- packages/ferdium-deb/ferdium-deb.pacscript
Closes https://github.com/pacstall/pacstall-programs/issues/1584
> add: `ferdium-deb`

- packagelist
- packages/nushell-bin/nushell-bin.pacscript
Adds [nushell](https://www.nushell.sh/)
> add: `nushell-bin`

- packages/mutt-wizard/mutt-wizard.pacscript
> upd(mutt-wizard): `3.2.1` -> `3.3.1`

- packages/os-installer-git/os-installer-git.pacscript
This time I've fully installed and check if it works fully.
> fix(os-installer-git): correctly install to /usr

- packages/smartgit/smartgit.pacscript
also remove the `replace alacritty` idk why it's there
> upd(smartgit): `21.2.2` -> `22.1.0`

- packages/couture/couture.pacscript
- packages/graillon/graillon.pacscript
- packages/panagement/panagement.pacscript
- packages/renegate/renegate.pacscript
I opened a yandex account back in 2020 or smth for the cheap storage and deleted it in 2021, I didn't know the email's still on here
> fix(various): echometerain change maintainer email

- packages/1password-cli-bin/1password-cli-bin.pacscript
> upd(1password-cli-bin): `2.11.0` -> `2.12.0`

- packages/discord-ptb-deb/discord-ptb-deb.pacscript
> upd(discord-ptb-deb): `0.0.35` -> `0.0.38`

- packages/arduino-ide-bin/arduino-ide-bin.pacscript
- packages/arduino-ide-bin/arduino-ide.desktop
closes #1929, closes #1991 
CI will probably fail since it cannot download the .desktop file
Edit: nevermind :)
> upd(arduino-ide-bin): `1.8.19` -> `2.0.3`

- packages/expressvpn-deb/expressvpn-deb.pacscript
> upd(expressvpn-deb): `3.27.1.0-1` -> `3.38.0.3-1`

- packages/anydesk-deb/anydesk-deb.pacscript
> upd(anydesk-deb) `6.2.0` -> `6.2.1`

- packages/aws-cli-v2-bin/aws-cli-v2-bin.pacscript
Fixes https://github.com/pacstall/pacstall-programs/issues/1930
Fixes https://github.com/pacstall/pacstall-programs/issues/1930
> upd(aws-cli-v2-bin): `2.9.9` -> `2.9.11`

- packages/windscribe-beta-gui-deb/windscribe-beta-gui-deb.pacscript
> upd(windscribe-beta-gui-deb): `2.4.8_beta` -> `2.5.12`

- packages/bitwig-studio-deb/bitwig-studio-deb.pacscript
Fixes https://github.com/pacstall/pacstall-programs/issues/1995
Fixes https://github.com/pacstall/pacstall-programs/issues/1933
> upd(bitwig-studio-deb): `4.4.0` -> `4.4.6`

- packages/rstudio-deb/rstudio-deb.pacscript
> upd(rstudio-deb): `2022.07.2+576` -> `2022.12.0+353`

- packages/qogir-gtk-theme-bin/qogir-gtk-theme-bin.pacscript
Fixes https://github.com/pacstall/pacstall-programs/issues/1971
> upd(qogir-gtk-theme-bin): `2021-12-25` -> `2022-11-09`

- packages/insync-deb/insync-deb.pacscript
cf. https://github.com/pacstall/pacstall-programs/issues/1952
> orphan(insync-deb)

- packages/latte-dock-git/latte-dock-git.pacscript
> fix(latte-dock-git): fix build errors

- packages/yandex-browser-beta-deb/yandex-browser-beta-deb.pacscript
> upd(yandex-browser-beta-deb): `22.5.0.1879-1` -> `22.11.3.832-1`

- packages/opera-developer-deb/opera-developer-deb.pacscript
> upd(opera-developer-deb): `90.0.4457.0` -> `96.0.4640.0`

- packages/opera-beta-deb/opera-beta-deb.pacscript
> upd(opera-beta-deb): `89.0.4447.20` -> `94.0.4606.19`

- packages/tenacity-git/tenacity-git.pacscript
https://codeberg.org/tenacityteam/tenacity/src/branch/main/BUILDING.md
> wxWidgets 3.1 is required but not packaged in Debian or Ubuntu
Actually, kinetic, lunar, bookworm, and sid have it
> fix(tenacity-git): update dependencies

- packages/obs-backgroundremoval-git/obs-backgroundremoval-git.pacscript
> fix(obs-backgroundremoval-git): fix for pacstall 3.1.1

- .github/workflows/tests.yml
cf. https://github.com/pacstall/pacstall-programs/pull/1878
fixes https://github.com/pacstall/pacstall-programs/issues/2105
> ci: do not fail out if 1 package fails for debian too

- packagelist
- packages/apx-git/apx-git.pacscript
closes https://github.com/pacstall/pacstall-programs/issues/2182
> add: `apx-git`

- packages/discord-canary/discord-canary.pacscript
I've also set myself as maintainer since the original maintainer seems to have gone inactive
> upd(discord-canary): `0.0.145` -> `0.0.146`

- packages/libxapp1-deb/libxapp1-deb.pacscript
Requires https://github.com/pacstall/pacstall-programs/pull/2219
> upd(libxapp1-deb): `2.4.1` -> `2.4.2`

- packagelist
- packages/powertop-git/powertop-git.pacscript
> add: `powertop-git`

- packagelist
- packages/internxt-deb/internxt-deb.pacscript
> add: `internxt-deb` (#2494

- packages/android-studio/android-studio.pacscript
> upd(android-studio): `2021.3.1.16` -> `2022.1.1.21`

- packagelist
- packages/quarto-deb/quarto-deb.pacscript
> add: `quarto-deb`

- packages/vivaldi-deb/vivaldi-deb.pacscript
Updated vivaldi from ``5.6.2867.50`` to ``5.7.2921.60-1``
> upd(vivaldi-deb): `5.6.2867.50` -> `5.7.2921.60`

- packagelist
- packages/cmake-deb/cmake-deb.pacscript
> add: `cmake-deb`

- packagelist
- packages/obs-backgroundremoval-0-4-0/obs-backgroundremoval-0-4-0.pacscript
Pin legacy version that is compatible with OBS 27, Ubuntu LTS, and Debian stable
> add: `obs-backgroundremoval-0-4-0`

- packagelist
- packages/enpass-deb/enpass-deb.pacscript
> add: `enpass-deb`

- packages/plexmediaserver-deb/plexmediaserver-deb.pacscript
> upd(plexmediaserver-deb): `1.27.1.5916-6b0e31a64` -> `1.32.0.6918-6f393eda1`

- packages/vscode-deb/vscode-deb.pacscript
update vscode to version 1.77.3
> upd(vscode-deb): `1.76.0` -> `1.77.3`

- packages/anydesk-bin/anydesk-bin.pacscript
> fix(anydesk-bin): properly install icons, part 2

- packagelist
- packages/xmind-vana-deb/xmind-vana-deb.pacscript
Closes #3204.
Homepage: https://xmind.app/
> add: `xmind-vana-deb`

- packages/truckersmp-cli/truckersmp-cli.pacscript
tested on linux mint 21.1, installs and builds
> upd(truckersmp-cli): `0.9.1.1` -> `0.10.0`

- packages/obs-backgroundremoval/obs-backgroundremoval.pacscript
Requires https://github.com/pacstall/pacstall-programs/pull/3304
> upd(obs-backgroundremoval): `0.5.16` -> `0.5.19`

- packagelist
- packages/goverlay/goverlay.pacscript
> add: `goverlay`

- packages/clipboard-bin/clipboard-bin.pacscript
> upd(clipboard-bin): `0.7.0` -> `0.7.1`

- packagelist
- packages/ticktick-deb/ticktick-deb.pacscript
> add: `ticktick-deb`

- packages/minecraft-pi-reborn-app/minecraft-pi-reborn-app.pacscript
Plus Repology so I don't forget.
> upd(minecraft-pi-reborn-app): `2.4.3` -> `2.4.8`

- packagelist
- packages/foliate-deb/foliate-deb.pacscript
> add: `foliate-deb`

- packages/unicorn-desktop-git/unicorn-desktop-git.pacscript
https://github.com/rhino-linux/unicorn/pull/4 must be merged first/before.
> upd(unicorn-desktop-git): package xsession

- packagelist
- packages/cheat/cheat.pacscript
> add: `cheat`

- packagelist
- packages/vscode-insiders-deb/vscode-insiders-deb.pacscript
> add: `vscode-insiders-deb`

- packagelist
- packages/megasync-deb/megasync-deb.pacscript
> add: `megasync-deb`

- packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
Closes https://github.com/an-anime-team/an-anime-game-launcher/issues/201
> upd(an-anime-game-launcher-bin): `3.7.0` -> `3.7.4`

- packages/telegram-bin/telegram-bin.pacscript
I'm not sure if it's allowed to switch maintainers, but if it's not, I'll be happy to revert the change, but still apply the update.
P.S.: The package is two commits away from being updated by third parties (other than the registered maintainer).
> upd(telegram-bin): `4.8.1` -> `4.8.4`

- packagelist
- packages/ananicy-cpp/ananicy-cpp.pacscript
> add: `ananicy-cpp`

- packages/yt-dlp/yt-dlp.pacscript
Also adds pyhack for pip install
> upd(yt-dlp): `2023.03.04` -> `2023.06.22`

- packagelist
- packages/genymotion-bin/genymotion-bin.pacscript
> add: `genymotion-bin`

- .github/workflows/tests.yml
depends on https://github.com/pacstall/pacstall/pull/942
> feat(CI): test arm64 packages, too

- packages/vscode-insiders-deb/vscode-insiders-deb.pacscript
The Insider package has updates that don't necessarily change the version, I don't know how to name it in PR, so: `internal release`
> upd(vscode-insiders-deb): `internal release`

- packagelist
- packages/bitwig-studio-4-deb/bitwig-studio-4-deb.pacscript
Pinned version for the people who didn't pay for the upgrade plan
> add: `bitwig-studio-4-deb`

- packages/rhino-pine-core/rhino-pine-core.pacscript
> upd(rhino-pine-core): `2023.1-beta7-0` -> `2023.1-beta7-1`

- packages/brave-browser-nightly-deb/brave-browser-nightly-deb.pacscript
> upd(brave-browser-nightly-deb): `1.58.35` -> `1.58.57`

- packagelist
- packages/owofetch/owofetch.pacscript
> add: `owofetch`

- packages/fastfetch-git/fastfetch-git.pacscript
Renamed libgio-cil to libgio3.0-cil
> fix(fastfetch-git): use proper dep

- .pre-commit-config.yaml
- packagelist
- packages/krita-app/krita-app.pacscript
> add: `krita-app`

- packages/linux-headers-okpine-deb/linux-headers-okpine-deb.pacscript
- packages/linux-image-okpine-deb/linux-image-okpine-deb.pacscript
- packages/linux-libc-dev-okpine-deb/linux-libc-dev-okpine-deb.pacscript
it wont boot on the pinetab2 with my defconfigs for some reason right now. just revert to a stable place
> fix(linux-okpine): `6.6.0-rc1` -> `6.5.0`

- packages/linux-headers-okpine-deb/linux-headers-okpine-deb.pacscript
- packages/linux-image-okpine-deb/linux-image-okpine-deb.pacscript
- packages/linux-libc-dev-okpine-deb/linux-libc-dev-okpine-deb.pacscript
> upd(linux-okpine): `6.5.0` -> `6.6.0-rc3`

- packages/rhino-core/rhino-core.pacscript
- packages/rhino-pine-core/rhino-pine-core.pacscript
- packages/rhino-server-core/rhino-server-core.pacscript
ubuntu dropped (development branch) from mantic so now we have to bump this
> upd(rhino*core): `2023.3-2` -> `2023.3-3`

- packagelist
- packages/deadbeef-deb/deadbeef-deb.pacscript
This package was requested in [issue  #4220](https://github.com/pacstall/pacstall-programs/issues/4220)
> add: `deadbeef-deb`

- packages/youtube-music-deb/youtube-music-deb.pacscript
I get update notification from it, so I report it updates from this PR
> upd(youtube-music-deb): `2.1.3` -> `2.2.0`

- packages/rhino-core/rhino-core.pacscript
- packages/rhino-pine-core/rhino-pine-core.pacscript
- packages/rhino-server-core/rhino-server-core.pacscript
- packages/rhino-ubxi-core/rhino-ubxi-core.pacscript
> upd(`rhino-*-core`): Remove compatibility with mantic

- packages/telegram-bin/telegram-bin.pacscript
- packages/youtube-music-deb/youtube-music-deb.pacscript
I think it's good to sync my local changes to Pacstall upstream repos
> upd(telegram-bin): `4.9.4` -> `4.11.1`

- packages/hypnotix-deb/hypnotix-deb.pacscript
Requires https://github.com/pacstall/pacstall-programs/pull/4695
> upd(hypnotix-deb): `3.6` -> `3.7`

- packagelist
- packages/virtualbox-deb/virtualbox-deb.pacscript
Pacstall Requested by @RandomnessRobin (PacReq: VirtualBox #4541)
> add: `virtualbox-deb`

- packagelist
- packages/tailscale/tailscale.pacscript
> add: `tailscale`

- packages/youtube-music-deb/youtube-music-deb.pacscript
I repair my mistakes in this PR
> upd(youtube-music-deb): `2.2.0` -> `3.0.2`

- packages/discord-deb/discord-deb.pacscript
> upd(discord-deb) `0.0.36` -> `0.0.38`

- packages/arduino-ide-bin/arduino-ide-bin.pacscript
Fixes usermod syntax in the message shown to the user. Also prevents the user variable from expanding and just shows the entire thing instead, since packages are installed as root.
> fix(arduino-ide-bin): Update serial interface command

- packages/librewolf-app/librewolf-app.pacscript
> fix(librewolf-app): fix package on `arm64`

- packages/librewolf-app/librewolf-app.pacscript
Also use `homedir` instead of `~`
> fix(librewolf-app): check if `~/.librewolf` exists before attempting to delete it

- packages/lf-bin/lf-bin.pacscript
And add all Debian-supported architectures
> upd(lf-bin): `30` -> `31`

- packages/topgrade-bin/topgrade-bin.pacscript
> fea(topgrade-bin): add arm64 support

- packages/neovim-app/neovim-app.pacscript
- packages/neovim/neovim.pacscript
https://github.com/neovim/neovim/releases/tag/v0.9.5
> upd(neovim{,-app}): `0.9.4` -> `0.9.5`

- packagelist
- packages/zig-bin/zig-bin.pacscript
Close https://github.com/pacstall/pacstall-programs/issues/5136
> add: `zig-bin`

- packages/goverlay/goverlay.pacscript
> upd(goverlay): `0.9.1` -> `1.0.0`

- packages/mangohud/mangohud.pacscript
> upd(mangohud): `0.6.9-1` -> `0.7.0`

- packages/git/git.pacscript
Upgrade git from 2.41.0 to 2.43.0
> upd(git): `2.41.0` -> `2.43.0`

- packages/yandex-browser-beta-deb/yandex-browser-beta-deb.pacscript
> upd(yandex-browser-beta-deb): `23.3.1.906-1` -> `23.11.1.675-1`

- packagelist
- packages/stockfish-git/stockfish-git.pacscript
> add:`stockfish-git`

- packages/heroic-games-launcher-deb/heroic-games-launcher-deb.pacscript
Updating from v2.11.0 to v2.12.0
> upd(heroic-games-launcher-deb): `2.11.0` -> `2.12.0`

- packages/electerm-deb/electerm-deb.pacscript
Changelog here: https://github.com/electerm/electerm/releases/tag/v1.38.8
> upd(electerm-deb): `1.37.110` -> `1.38.8`

- packages/oh-my-posh-git/oh-my-posh-git.pacscript
cf https://github.com/JanDeDobbeleer/oh-my-posh/issues/4655
> fix(oh-my-posh-git): build needs go 1.21

- packages/arduino-ide-bin/arduino-ide-bin.pacscript
I wish this package maintainer allow me to help update this pacscript
> upd(arduino-ide-bin): 2.2.1 -> 2.3.0

- packages/apx-git/apx-git.pacscript
in apx.json, the distrobox path was not correct anymore.
> fix(apx-git): incorrect distrobox path 

- packages/helix/helix.pacscript
> chore(helix): orphan

- packages/brave-browser-deb/brave-browser-deb.pacscript
> upd(brave-browser-deb):`1.61.114`->`1.63.162`

- packages/adw-gtk3/adw-gtk3.pacscript
hopefully dyslexia didn't take into effect yet
> upd(adw-gtk3) `4-9` -> `5.3`

- packagelist
- packages/libfdk-aac1-deb/libfdk-aac1-deb.pacscript
> add: `libfdk-aac1-deb`

- packagelist
- packages/the-honkers-railway-launcher-bin/the-honkers-railway-launcher-bin.pacscript
> add: `the-honkers-railway-launcher-bin`

- packages/git-delta-deb/git-delta-deb.pacscript
Update git-delta package to version 0.17.0.
> upd(git-delta-deb): `0.16.5` -> `0.17.0`

- packagelist
- packages/naps2-deb/naps2-deb.pacscript
> add: `naps2-deb`

- packagelist
- packages/flyctl-bin/flyctl-bin.pacscript
Add a package for the fly.io command line client
> add: `flyctl-bin`

- packages/protonup-qt-app/protonup-qt-app.pacscript
I've tested and installed it locally and it worked.
> upd(protonup-qt-app): `2.9.1` -> `2.9.2`

- packagelist
- packages/libxcb-errors/libxcb-errors.pacscript
- packages/xcb-util-errors/xcb-util-errors.pacscript
> add: `xcb-util-errors`

- packages/rhino-core/rhino-core.pacscript
- packages/rhino-pine-core/rhino-pine-core.pacscript
- packages/rhino-server-core/rhino-server-core.pacscript
- packages/rhino-ubxi-core/rhino-ubxi-core.pacscript
> fix(rhino*core): repair loop with `base-files`

- packages/rhino-core/rhino-core.pacscript
- packages/rhino-pine-core/rhino-pine-core.pacscript
- packages/rhino-server-core/rhino-server-core.pacscript
- packages/rhino-ubxi-core/rhino-ubxi-core.pacscript
I guess the issue was just `--no-rename` and not also `post_remove`. no idea man.
> fix(rhino*core): repair swapping between each other

- packages/nushell-bin/nushell-bin.pacscript
fixes a dependency issue in 5.0.0
> fix(nushell-bin): `pkgname` -> `fake_gives`

- packages/hamclock/hamclock.pacscript
Ran shfmt on hamclock to have correct whitespace.
> fix(hamclock): `shfmt`

- packages/teamviewer-deb/teamviewer-deb.pacscript
> upd(teamviewer-deb): `15.51.5` -> `15.53.6`

- packages/steam-deb/steam-deb.pacscript
fixed unneeded pacdep, fixed version. In this case, hash is useless but I have updated it.
> upd(steam-deb): `1.0.0.78` -> `1.0.0.79`

- packagelist
- packages/goldberg-emulator-git/.SRCINFO
- packages/goldberg-emulator-git/goldberg-emulator-git.pacscript
NOTE: Don't merge until the `source` migration.
> add: `goldberg-emulator-git`

- packages/android-studio/.SRCINFO
- packages/android-studio/android-studio.pacscript
> upd(android-studio): `2023.2.1.25` -> `2024.1.1.6`

- packages/aws-cli-v2-bin/.SRCINFO
- packages/aws-cli-v2-bin/aws-cli-v2-bin.pacscript
> upd(aws-cli-v2-bin): `2.15.13` -> `2.15.44`

- packages/chezmoi-deb/.SRCINFO
- packages/chezmoi-deb/chezmoi-deb.pacscript
> upd(chezmoi-deb): `2.47.2` -> `2.48.0`

- packages/google-chrome-unstable-deb/.SRCINFO
- packages/google-chrome-unstable-deb/google-chrome-unstable-deb.pacscript
> upd(google-chrome-unstable-deb): `122.0.6253.3` -> `126.0.6452.3`

- packages/chwp-deb/.SRCINFO
- packages/chwp-deb/chwp-deb.pacscript
> upd(chwp-deb): `1.217.0` -> `1.239.6`

- packages/nordvpn-deb/.SRCINFO
- packages/nordvpn-deb/nordvpn-deb.pacscript
> upd(nordvpn-deb): `3.17.0` -> `3.17.4`

- packages/opera-developer-deb/.SRCINFO
- packages/opera-developer-deb/opera-developer-deb.pacscript
> upd(opera-developer-deb): `108.0.5054.0` -> `111.0.5151.0`

- packages/sublime-merge-deb/.SRCINFO
- packages/sublime-merge-deb/sublime-merge-deb.pacscript
> upd(sublime-merge-deb): `2092` -> `2096`

- packages/topgrade-musl-bin/.SRCINFO
- packages/topgrade-musl-bin/topgrade-musl-bin.pacscript
> upd(topgrade-musl-bin): `14.0.0` -> `14.0.1`

- packages/webcord-deb/.SRCINFO
- packages/webcord-deb/webcord-deb.pacscript
> upd(webcord-deb): `4.6.1` -> `4.9.1`

- packages/hamclock-big/.SRCINFO
- packages/hamclock-big/hamclock-big.pacscript
- packages/hamclock-big/hamclock.desktop
I made a mistake in the desktop shortcut, so this is to fix that before adding the source file for the next PR.
> fix(hamclock-big): fix the desktop shortcut

- packages/wgcf-bin/.SRCINFO
- packages/wgcf-bin/wgcf-bin.pacscript
Updating wgcf from 2.2.20 to 2.2.22
> upd(wgcf-bin): `2.2.20` -> `2.2.22`

- packages/hamclock-bigger/.SRCINFO
- packages/hamclock-bigger/hamclock-bigger.pacscript
Also updated the tarball source to be consistent with AUR.
> upd(hamclock-bigger): `4.00` -> `4.01`

- packages/hamclock-huge/.SRCINFO
- packages/hamclock-huge/hamclock-huge.pacscript
Also updated the tarball source to be consistent with AUR.
> upd(hamclock-huge): `4.00` -> `4.01`

- packages/pacup-git/.SRCINFO
- packages/pacup-git/pacup-git.pacscript
- packages/pacup/.SRCINFO
- packages/pacup/pacup.pacscript
> upd(pacup{-git}): `3.1.3` -> `3.2.0`

- packages/stockfish-git/.SRCINFO
- packages/stockfish-git/stockfish-git.pacscript
Fixed the pacscript to be more up to date with the recent changes to make it build correctly. As pointed out, I also enabled internet so that the package can download the weights needed. Also changed my email.
> fix(stockfish-git): repair `build()` function

- packages/lazygit/.SRCINFO
- packages/lazygit/lazygit.pacscript
> upd(lazygit): `0.40.2` -> `0.42.0`

- packages/chezmoi-deb/.SRCINFO
- packages/chezmoi-deb/chezmoi-deb.pacscript
> upd(chezmoi-deb): `2.48.0` -> `2.48.2`

- packages/starship-bin/.SRCINFO
- packages/starship-bin/starship-bin.pacscript
Update starship-bin to latest stable.
> upd(starship-bin): `1.16.0` -> `1.19.0`

- packages/ulauncher-deb/.SRCINFO
- packages/ulauncher-deb/ulauncher-deb.pacscript
Update of Ulauncher beta10 to beta13. Fixes issues that using enter after searching wouldn't actually execute.
> upd(ulauncher): `6.0.0~beta10` -> `6.0.0~beta13`

- packagelist
- packages/grub-btrfs/.SRCINFO
- packages/grub-btrfs/grub-btrfs.pacscript
Include btrfs snapshots in GRUB boot options
> add: `grub-btrfs`

- hyfetch-git/hyfetch-git.pacscript
Hi, I have added hyfetch-git, based upon https://github.com/hykilpikonna/hyfetch/ & https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=hyfetch-git
> add: `hyfetch-git`

- packagelist
- packages/snapper-rollback-git/.SRCINFO
- packages/snapper-rollback-git/snapper-rollback-git.pacscript
Script to rollback snapper snapshots as described here https://wiki.archlinux.org/index.php/Snapper#Suggested_filesystem_layout
> add: `snapper-rollback-git`

- packagelist
- packages/typora-deb/.SRCINFO
- packages/typora-deb/typora-deb.pacscript
A minimal markdown editor and reader.
> add: `typora-deb`

- packages/the-honkers-railway-launcher-bin/.SRCINFO
- packages/the-honkers-railway-launcher-bin/the-honkers-railway-launcher-bin.pacscript
Updated to `1.6.1`, also tested and worked locally on my PC.
> upd(the-honkers-railway-launcher-bin): `1.6.0` ->  `1.6.1`

- packages/an-anime-game-launcher-bin/.SRCINFO
- packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
Updated to `3.10.1`, tested and worked fine locally on my PC.
> upd(an-anime-game-launcher-bin): `3.10.0` -> `3.10.1`

- scripts/srcinfo.sh
> ci(srcinfo.sh): add missing overrides

- packages/pacup/.SRCINFO
- packages/pacup/pacup.pacscript
> upd(pacup): `3.2.0` -> `3.3.0`

- packages/pacup/.SRCINFO
- packages/pacup/pacup.pacscript
> upd(pacup): `3.3.0` -> `3.3.1`

- packages/pacup/.SRCINFO
- packages/pacup/pacup.pacscript
> upd(pacup): `3.3.1` -> `3.3.2`

- packages/pacup-git/.SRCINFO
- packages/pacup-git/pacup-git.pacscript
> upd(pacup-git): `3.3.1` -> `3.3.2`

- packages/android-studio/.SRCINFO
- packages/android-studio/android-studio.pacscript
- srclist
> upd(android-studio): `2024.1.1.6` -> `2024.1.1.12`

- packages/an-anime-game-launcher-bin/.SRCINFO
- packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript
- srclist
- Updated to `3.11.0`
Had been tested locally, confirm working (at least on my side).
> upd(an-anime-game-launcher-bin): `3.10.3` -> `3.11.0`

- packagelist
- packages/honkers-launcher-bin/.SRCINFO
- packages/honkers-launcher-bin/honkers-launcher-bin.pacscript
- srclist
* Added `honkers-launcher-bin.pacscript` and `.SRCINFO`
Tested locally, everything seems to be working.
> add: `honkers-launcher-bin`

- packages/discord-deb/.SRCINFO
- packages/discord-deb/discord-deb.pacscript
- srclist
Update Discord : 0.0.64 to 0.0.65"
> upd(discord-deb): `0.0.64` -> `0.0.65`

- packages/apx-git/.SRCINFO
- packages/apx-git/apx-git.pacscript
- srclist
to declare incompatible with bookworm
> fix(apx-git): declare `incompatible` with bookworm

- packages/lunacy-deb/.SRCINFO
- packages/lunacy-deb/lunacy-deb.pacscript
- srclist
Now I want to update the `lunacy-deb` from branch `pr-branch-1`. The version updated from `9.5.0` into `10.1`. Please review immediately when everything's okay.
> upd(lunacy-deb): `9.5.0` --> `10.1` 

- packagelist
- packages/amf-headers/.SRCINFO
- packages/amf-headers/amf-headers.pacscript
- srclist
Adds amf-headers needed for future ffmpeg-full builds
> add: `amf-headers`

- packages/zed-editor-preview-bin/.SRCINFO
- packages/zed-editor-preview-bin/zed-editor-preview-bin.pacscript
- packages/zed-editor-stable-bin/.SRCINFO
- packages/zed-editor-stable-bin/zed-editor-stable-bin.pacscript
- srclist
UPD: *sigh* messed sha256sums, gonna fix...
UPD1: fixed
> upd(zed-editor-{stable,preview}-bin): `0.154.3` -> `0.154.4`, `0.155.1` -> `0.155.2`

- packages/librewolf-deb/.SRCINFO
- packages/librewolf-deb/librewolf-deb.pacscript
- srclist
I re-commit this based on mistaken on previous commit. Now ready to merge.
> upd(librewolf-deb): `130.0-3` -> `130.0.1-1`

- packagelist
- packages/icecat-deb/.SRCINFO
- packages/icecat-deb/icecat-deb.pacscript
- srclist
Based on my requests #6505. Close it as complete for request once my commit are merged.
> add: `icecat-deb`

- packages/lunacy-deb/.SRCINFO
- packages/lunacy-deb/lunacy-deb.pacscript
- srclist
Another Lunacy update which refrenced from [this](https://lunacy.docs.icons8.com/release-notes/#1030)
> upd(lunacy-deb): `10.1` -> `10.3`

- packages/pycharm-community-bin/.SRCINFO
- packages/pycharm-community-bin/pycharm-community-bin.pacscript
- srclist
Just updating Pycharm as latest version 2024.2.3 which released on August.
Please merge the commit when everything's okay
> upd(pycharm-community-bin): `2023.2.5` -> `2024.2.3`

- packagelist
- packages/thunderbird-bin/.SRCINFO
- packages/thunderbird-bin/thunderbird-bin.pacscript
- srclist
> add: `thunderbird-bin`

- packages/wgcf-bin/.SRCINFO
- packages/wgcf-bin/wgcf-bin.pacscript
- srclist
> upd(wgcf-bin): `2.2.22` -> `2.2.23`

- packages/lunacy-deb/.SRCINFO
- packages/lunacy-deb/lunacy-deb.pacscript
- srclist
Just updating the versions, probably will be drafted firsts (but it will fix the sums later and ready to merge when everything's okay in this commit).
> upd(lunacy-deb): `10.3` -> `10.5`

- packages/librewolf-deb/.SRCINFO
- packages/librewolf-deb/librewolf-deb.pacscript
- srclist
> upd(librewolf-deb): `131.0.3-1` -> `132.0-1`

- packages/zig-bin/.SRCINFO
- packages/zig-bin/zig-bin.pacscript
- srclist
> upd(zig-bin): `0.12.0` -> `0.13.0`

- packages/moka-icon-theme/.SRCINFO
- packages/moka-icon-theme/moka-icon-theme.pacscript
- srclist
dont really care if the package build process works on this, just need its link to conform...
> fix(moka-icon-theme): use proper link

- packages/discord-canary/.SRCINFO
- packages/discord-canary/discord-canary.pacscript
- srclist
> upd(discord-canary): `0.0.327` -> `0.0.528`

- packages/librewolf-deb/.SRCINFO
- packages/librewolf-deb/librewolf-deb.pacscript
- srclist
> upd(librewolf-deb): `132.0.2-1` -> `133.0-1`

- packages/firefox-developer-edition-bin/.SRCINFO
- packages/firefox-developer-edition-bin/firefox-developer-edition-bin.pacscript
- srclist
Another updates for Firefox Developer Edition (I pick 134.0b7 as latest version from the time I create the commit)
> upd(firefox-developer-edition-bin): `133.0b8` -> `134.0b7`

- packages/lunacy-deb/.SRCINFO
- packages/lunacy-deb/lunacy-deb.pacscript
- srclist
Just updating Lunacy which based on [10.9 releases of Lunacy](https://lunacy.docs.icons8.com/release-notes/#109).
> upd(lunacy-deb): `10.5` -> `10.9`

- packages/intellij-idea-community-bin/.SRCINFO
- packages/intellij-idea-community-bin/intellij-idea-community-bin.pacscript
- srclist
Updates for IDEA Community on 2024.3.1
> upd(intellij-idea-community-bin): `2024.2.3` -> `2024.3.1`

- packages/xfce4-dynamic-workspaces-plugin-git/xfce4-dynamic-workspaces-plugin-git.pacscript
https://github.com/pacstall/pacstall-programs/pull/6720#issuecomment-2525302732
> fix(xfce4-dynamic-workspaces-plugin-git): change `ln` to `cp`

- packagelist
- packages/obs-studio-deb/.SRCINFO
- packages/obs-studio-deb/obs-studio-deb.pacscript
- srclist
> add: `obs-studio-deb`

- packages/zotero/.SRCINFO
- packages/zotero/zotero.pacscript
- srclist
> upd(zotero): `7.0.9` -> `7.0.11`

- packages/discord-canary/.SRCINFO
- packages/discord-canary/discord-canary.pacscript
- packages/discord-deb/.SRCINFO
- packages/discord-deb/discord-deb.pacscript
- packages/discord-ptb-deb/.SRCINFO
- packages/discord-ptb-deb/discord-ptb-deb.pacscript
- packages/discord/.SRCINFO
- packages/discord/discord.pacscript
- srclist
* discord: `0.0.49` -> `0.0.78`
* discord-deb: `0.0.72` -> `0.0.78`
* discord-ptb-deb: `0.0.54` -> `0.0.124`
* discord-canary: `0.0.528` -> `0.0.550`
> upd(discord*): update to latest

- packages/pycharm-community-bin/.SRCINFO
- packages/pycharm-community-bin/pycharm-community-bin.pacscript
- packages/pycharm-community-bin/pycharm.desktop
- srclist
This update of `pycharm-community-bin` are bringing new updates from `2024.3` into `2024.3.1.1` with several changes for pacscripts.
> upd(pycharm-community-bin): `2024.3` -> `2024.3.1.1`

- packages/youtube-music-deb/.SRCINFO
- packages/youtube-music-deb/youtube-music-deb.pacscript
- srclist
Another updates for th-ch's YTM apps.
> upd(youtube-music-deb): `3.6.2` -> `3.7.1`

- packages/webstorm-bin/.SRCINFO
- packages/webstorm-bin/webstorm-bin.pacscript
- srclist
Minor updates for WebStorm (`webstorm-bin`) on `2024.3.1.1`
> upd(webstorm-bin): `2024.3.1` -> `2024.3.1.1`

- packages/firefox-developer-edition-bin/.SRCINFO
- packages/firefox-developer-edition-bin/firefox-developer-edition-bin.pacscript
- srclist
_I forget to tell it._
It's another minor updates for Firefox Dev Edition.
> upd(firefox-developer-edition-bin): `134.0b7` -> `134.0b9`

- packages/intellij-idea-community-bin/.SRCINFO
- packages/intellij-idea-community-bin/intellij-idea-community-bin.pacscript
- packages/intellij-idea-community-bin/intellij-idea-community.desktop
- srclist
Yeah, updates coming for Intellij IDEA Community (and also I give a changes for the scripts). This update will Closes #6731.
> upd(intellij-idea-community-bin): `2024.3.1` -> `2024.3.1.1`

- packages/thunderbird-bin/.SRCINFO
- packages/thunderbird-bin/thunderbird-bin.pacscript
- srclist
Another updates for Thunderbird standard release.
> upd(thunderbird-bin): `131.0.1` -> `133.0`

- packages/discord-canary-deb/.SRCINFO
- packages/discord-canary-deb/discord-canary-deb.pacscript
- packages/discord-canary/.SRCINFO
- packages/discord-canary/discord-canary.pacscript
- srclist
- discord-canary: `0.0.556` -> `0.0.558`
- discord-canary-deb: `0.0.556` -> `0.0.558`
> upd(discord-canary*): `0.0.556` -> `0.0.558`

- packagelist
- packages/cloudflare-warp-deb/.SRCINFO
- packages/cloudflare-warp-deb/cloudflare-warp-deb.pacscript
- srclist
> add: `cloudflare-warp-deb`

- packages/discord-canary-deb/.SRCINFO
- packages/discord-canary-deb/discord-canary-deb.pacscript
- packages/discord-canary/.SRCINFO
- packages/discord-canary/discord-canary.pacscript
- srclist
- discord-canary: `0.0.559` -> `0.0.565`
- discord-canary-deb: `0.0.558` -> `0.0.565`
> upd(discord-canary*): `0.0.558` -> `0.0.565`

- packages/android-studio/.SRCINFO
- packages/android-studio/android-studio.pacscript
- srclist
Another updates for Android Studio (Still Ladybug but with new updates).
> upd(android-studio): `2024.2.1.11` -> `2024.2.2.13`

- packages/lunacy-deb/.SRCINFO
- packages/lunacy-deb/lunacy-deb.pacscript
- srclist
Yet another updates for Lunacy from 10.9 into 10.11 from Icons8.
> upd(lunacy-deb): `10.9` -> `10.11`

- packages/discord-canary-deb/.SRCINFO
- packages/discord-canary-deb/discord-canary-deb.pacscript
- packages/discord-canary/.SRCINFO
- packages/discord-canary/discord-canary.pacscript
- packages/discord-ptb-deb/.SRCINFO
- packages/discord-ptb-deb/discord-ptb-deb.pacscript
- srclist
- discord-ptb-deb: `0.0.126` -> `0.0.127`
- discord-canary: `0.0.567` -> `0.0.574`
- discord-canary-deb: `0.0.567` -> `0.0.574`
> upd(discord-*): update to latest

- packages/android-studio/android-studio.pacscript
> fix(android-studio): switch to the native launcher

- packagelist
- packages/rojo-bin/.SRCINFO
- packages/rojo-bin/rojo-bin.pacscript
- srclist
> add: `rojo-bin`

- packages/floorp-bin/.SRCINFO
- packages/floorp-bin/floorp-bin.pacscript
- srclist
> fix(floorp-bin): do not cd into srcdir

- packages/rambox-deb/.SRCINFO
- packages/rambox-deb/rambox-deb.pacscript
- srclist
Another updates for Rambox (deb versions).
> upd(rambox-deb): `2.3.4` -> `2.4.1`

- packages/clio-git/.SRCINFO
- packages/clio-git/clio-git.pacscript
- srclist
> upd(clio-git): `1.0` -> `1.2.0`

- packages/firefox-bin/.SRCINFO
- packages/firefox-bin/firefox-bin.pacscript
- srclist
See: https://support.mozilla.org/en-US/kb/speechd-setup
> fix(firefox-bin): add `speech-dispatcher` optdep

- packages/pycharm-community-bin/.SRCINFO
- packages/pycharm-community-bin/pycharm-community-bin.pacscript
- srclist
Another updates for Pycharm Community Edition.
> upd(pycharm-community-bin): `2024.3.1.1` -> `2024.3.3`

- packages/rustrover-bin/.SRCINFO
- packages/rustrover-bin/rustrover-bin.pacscript
- srclist
Another updates for RustRover.
> upd(rustrover-bin): `2024.3.3` -> `2024.3.4`

- packagelist
- packages/soar/.SRCINFO
- packages/soar/soar.pacscript
- srclist
Tested with the docker by running:
```bash
./pacstall-docker-builder --distro ubuntu:devel --version master --test
```
> add: `soar`

- packages/youtube-music-deb/.SRCINFO
- packages/youtube-music-deb/youtube-music-deb.pacscript
- srclist
For some reason, 3.7.1 did not get installed properly for me, but bumping the version to 3.7.5 somehow helped.
> upd(youtube-music-deb): `3.7.1` -> `3.7.5`

- packages/discord/.SRCINFO
- packages/discord/discord.pacscript
- srclist
Also adds optional dependency for emoji support
> fix(discord): executable perms and update

- packagelist
- packages/abdownloadmanager/.SRCINFO
- packages/abdownloadmanager/abdownloadmanager.pacscript
- srclist
> add: `abdownloadmanager`

- packages/ungoogled-chromium-bin/.SRCINFO
- packages/ungoogled-chromium-bin/ungoogled-chromium-bin.pacscript
- srclist
Another updates for Ungoogled Chromium
> upd(ungoogled-chromium-bin): `132.0.6834.110-1` -> `134.0.6998.35-1`

- packages/lunacy-deb/.SRCINFO
- packages/lunacy-deb/lunacy-deb.pacscript
- srclist
Another updates for Lunacy into 11.0
> upd(lunacy-deb): `10.11` -> `11.0`

- packagelist
- packages/audiorelay-bin/.SRCINFO
- packages/audiorelay-bin/audiorelay-bin.pacscript
- srclist
> add: `audiorelay-bin`

- packages/thorium-deb/.SRCINFO
- packages/thorium-deb/thorium-deb.pacscript
- srclist
Another updates for Thorium (amd64).
> upd(thorium-deb): `128.0.6613.189` -> `130.0.6723.174`

- packagelist
- packages/lynxfetch/.SRCINFO
- packages/lynxfetch/lynxfetch.pacscript
- srclist
> add: `lynxfetch`

- packages/ferium-bin/.SRCINFO
- packages/ferium-bin/ferium-bin.pacscript
- srclist
Fixes https://github.com/gorilla-devs/ferium/issues/460.
> upd(ferium-bin): `4.7.0` -> `4.7.1`

- packages/floorp-bin/.SRCINFO
- packages/floorp-bin/floorp-bin.pacscript
- srclist
Updated floorp-bin from ``v11.22.0`` to ``v11.24.0``
> upd(floorp-bin) `v11.22.0` -> `v11.24.0`

- packages/lynxfetch/.SRCINFO
- packages/lynxfetch/lynxfetch.pacscript
- srclist
> upd(lynxfetch): `1.0.6` -> `1.0.7`

- packagelist
- packages/geekbench6-bin/.SRCINFO
- packages/geekbench6-bin/geekbench6-bin.pacscript
- srclist
In reference to https://github.com/pacstall/pacstall-programs/pull/7139 and https://github.com/pacstall/pacstall-programs/pull/7194
> add: `geekbench6-bin`

- packages/krita-app/.SRCINFO
- packages/krita-app/krita-app.pacscript
- srclist
I have changed the scripts and make it simple. Also, this updates are for Krita from `5.1.5` into `5.2.9`.
> upd(krita-app): `5.1.5` -> `5.2.9`

- packages/zen-browser-bin/.SRCINFO
- packages/zen-browser-bin/zen-browser-bin.pacscript
- srclist
> fix(zen-browser-bin): changed hashsums

- packagelist
- packages/typescript/.SRCINFO
- packages/typescript/typescript.pacscript
- srclist
Ported from official Arch Linux "extra" repository.
> add: `typescript`

- packages/hamclock-big/.SRCINFO
- packages/hamclock-big/hamclock-big.pacscript
- packages/hamclock-bigger/.SRCINFO
- packages/hamclock-bigger/hamclock-bigger.pacscript
- packages/hamclock-huge/.SRCINFO
- packages/hamclock-huge/hamclock-huge.pacscript
- packages/hamclock/.SRCINFO
- packages/hamclock/hamclock.pacscript
- srclist
I converted the less than great sed "patch" parts into proper patches I'll maintain moving forward. I had to get the same working at Arch AUR properly as well before updating the packages here.
Thanks!
> upd(hamclock{,-big,-bigger,-huge}): `4.15` -> `4.19`

- packages/thunderbird-bin/.SRCINFO
- packages/thunderbird-bin/thunderbird-bin.pacscript
- srclist
File extension is now changed from .tar.bz2 -> tar.xz
> upd(thunderbird-bin): `133.0` -> `140.0.1`

- packagelist
- packages/fblog-bin/.SRCINFO
- packages/fblog-bin/fblog-bin.pacscript
- srclist
> add: `fblog-bin`

- packages/floorp-bin/.SRCINFO
- packages/floorp-bin/floorp-bin.pacscript
- srclist
- changed tar.bz2 -> tar.xz.
- release for arm64 is discontinued.
> upd(floorp-bin): `11.27.0` -> `12.0.15`

- packagelist
- packages/libfdk-aac-dev-deb/.SRCINFO
- packages/libfdk-aac-dev-deb/libfdk-aac-dev-deb.pacscript
- srclist
> add: `libfdk-aac-dev-deb`

- packagelist
- packages/imhex-app/.SRCINFO
- packages/imhex-app/imhex-app.pacscript
- srclist
> add: `imhex-app`
