pacstall/pacstall-programs

packages/discord/discord.pacscript

Discord sometimes can't auto update on linux due to having to change files in directories outside the home directory which it can't because of permissions. Recently version 0.0.15 was released.

Update Discord Version to 0.0.15

---

packages/soundux/soundux.pacscript

This now installs the doc, license and a binary symlink that it can be started via `soundux` in the terminal

Update Soundux pacscript

---

packages/bat/bat.pacscript

I don't use Pacstall anymore, so setting the maintainer to orphaned. 
There is a new release of Bat, but someone else need to pick up the torch.

Set maintainer to orphaned

---

packages/planner-git/planner-git.pacscript

it's not available on LTS but planner needs it to work

Change libhandy to version 1

---

packages/bpytop-git/bpytop-git.pacscript

Fixes `bpytop-git`'s `psutil` installation. Previously if an older `psutil` version was installed then it was not updated. Which resulted in breakage. This fixes that.
Maintainer: @WRM-42

fix(bpytop-git): Add `--upgrade` flag

---

packages/librewolf-app/librewolf-app.pacscript

Updates librewolf, uses generic URL from now on. So if a new version releases and I don't update in time, the package doesn't install (hash mismatch), so users always get the latest librewolf or no librewolf at all.

upd(librewolf-app): `92.0-1` -> `92.0.1-1`

---

.github/workflows/test-package-install.yml

Axel causes the CI to fail downloading the source for a package.
I verified it is axels fault due to the line in the CI, where it say’s `error opening local file`
https://github.com/haileys/axel/blob/8e8eeb0650a097213d1b439e98629dfc6e709af9/axel.c#L178

Remove Axel from CI

---

packages/brave-browser-deb/brave-browser-deb.pacscript

https://www.bleepingcomputer.com/news/security/google-pushes-emergency-chrome-update-to-fix-zero-day-used-in-attacks/
https://github.com/brave/brave-browser/releases/tag/v1.33.106

upd(brave-browser-deb): `1.32.115` -> `1.33.106`

---

packages/neovim/neovim.pacscript

This fixes the recursive install issue with neovim and updates to 0.6.0

upd(neovim): `0.5.0` -> `0.6.0`

---

packagelist
packages/dust-bin/dust-bin.pacscript

add: `dust-bin`

---

README.md

Hi,
This is just a small proposition that in my opinion makes the navigation easier from the packages repo to the manager repo, and might help newcomers.

docs(readme): add link to pacstall repo

---

packages/nano/nano.pacscript

Replace `make` position to avoid wrong first match substitution (`automake -> auto`)

fix(nano):  make and automake edge case

---

packagelist
packages/amdgpu-dkms-firmware-deb/amdgpu-dkms-firmware-deb.pacscript

Will be used soon for aomp-deb eventually.

add: `amdgpu-dkms-firmware-deb`

---

packagelist
packages/tidal-hifi-bin/tidal-hifi-bin.pacscript

This would add the AUR package [tidal-hifi-bin](https://aur.archlinux.org/packages/tidal-hifi-bin) previously called tidal-hifi before the change to -bin to pacstall.

add: `tidal-hifi-bin`

---

packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript

Henry once mentioned this in our discord that the script should ask for removal of the launcher's data folder and I didn't realize until now that librewolf already had a perfectly working example.

fix(an-anime-game-launcher-bin): add removescript

---

.github/labeler.yml
.github/workflows/main.yml

Make labeler only trigger on the PR itself and not on every PR commit, Fix the regex for title detection as it was missing the ^

ci(github): change trigger for labeler and fix title detection

---

.github/labeler.yml

( gets detected by regex as the beginning of a group structure without escape stringing it

ci(github): fix regex for Update Package

---

packages/bottles/bottles.pacscript

Due to the nature of Bottles releasing fixes under (date)-(version code name)-(patch number) I have decided to put it in version removing the need to update url

upd(bottles): `2022.5.2` -> `2022.5.2-trento-3`

---

packagelist
packages/torbrowser-launcher-deb/torbrowser-launcher-deb.pacscript

I'm not a big fan of using an unofficial source for security reasons

rm: `torbrowser-launcher-deb`

---

packages/neovim-git/neovim-git.pacscript

1. There are 3 types of builds and the default one is `Debug`, which is the slowest.
2. As recommended by neovim team, there is no need to use `-j` flag, since it will run in parallel anyways.
See: https://github.com/neovim/neovim/wiki/Building-Neovim#building

Fix(neovim-git): optimize build

---

packagelist
packages/qtile-extras-git/qtile-extras-git.pacscript

- Added `qtile-extras-git` to the list of supported packages.
- Added `qtile-extras-git.pacscript`.
- Updated the `packagelist`.
The package `qtile-extras-git` installs `qtile-git` as a dependency, but I am not sure as to, how to uninstall `qtile-git`, when `$ pacstall -R qtile-extras-git` is called. I was thinking that running `pacstall -R qtile-git` in the `removescript` function, would do the job, is this the right way, if not please let me know how I should do this.
Thanks

add: `qtile-extras-git`

---

packages/bottles/bottles.pacscript

Bottles is now gtk4 + libadwaita! So the dependencies will probably be updated.

upd(bottles): `2022.5.28-trento-3` -> `2022.6.14-brescia`

---

packages/aws-cli-v2-bin/aws-cli-v2-bin.pacscript

Maintainer also changed due to the last update by original maintainer being when the package was originally added

upd(aws-cli-v2-bin): `2.7.6` -> `2.7.10`

---

packages/vscodium-deb/vscodium-deb.pacscript

Also fixed url (there seems to be a change in the last set of digits)

upd(vscodium-deb): `1.68.0` -> `1.68.1`

---

packages/vscodium-deb/vscodium-deb.pacscript

Seems like the url has changed here as well.

upd(vscodium-deb): v1.68.1 -> v1.69.0

---

packages/bitwarden-deb/bitwarden-deb.pacscript

It seems that the [bitwarden-desktop repology entry](https://repology.org/project/bitwarden-desktop/versions) is not updated as often as the [bitwarden repology entry](https://repology.org/project/bitwarden/versions) so I have changed the `bitwarden-deb` package to use the latter. Note that this pacstall package appears under the new repology entry (and *not* the old one). I have also checked a few other package repositories to confirm that their packages are for the desktop app (as opposed to the CLI tool or something else related to bitwarden).

fix(bitwarden-deb): change repology

---

packages/vscodium-deb/vscodium-deb.pacscript

it is seeming like the numbers in the url are changing every time.

upd(vscodium-deb): `1.69.0` -> `1.69.1`

---

packagelist
packages/arduino-ide-bin/arduino-ide-bin.pacscript

Adds `arduino-ide-bin`, version `1.8.19`.
I considered adding commands to `postinst` to add the user to the "uucp" and "dialout" groups, which is usually required to access the Arduino's serial interface as a regular user (also see [this](https://playground.arduino.cc/Linux/All/#Permission)). However, since this is user-specific and the program is installed system-wide, I decided against this.
I can still add it if desired, but the IDE should also point users to the article above if it detects a permission issue, so I'm not sure if it's necessary.

add: `arduino-ide-bin`

---

packages/postman-bin/postman-bin.pacscript

This update also changes the download link to postman's download server as they fixed their download api recently

upd(postman-bin): `9.25.2` -> `9.27.0`

---

packages/go-bin/go-bin.pacscript

Tested working on my machine:
```sh
$ pacstall -Il go-bin.pacscript
$ go version
go version go1.19 linux/amd64
$ echo 'package main;import "fmt";func main(){fmt.Println("Hello, world")}' >> /tmp/test.go
Hello, world
```

upd(go-bin): `1.18.3` -> `1.19`

---

packages/discord-canary/discord-canary.pacscript

Also fixes incorrect naming of the icon png, causing the desktop icon to be missing.

upd(discord-canary): `0.0.136` -> `0.0.137`

---

packages/zap/zap.pacscript

Add initial pacstall script for zap appimage package manager. Related to [this issue](https://github.com/srevinsaju/zap/issues/82).
The script is very basic and just relies on the curl-based shell script that [zap](https://github.com/srevinsaju/zap) itself uses to setup and install itself.

add: `zap`

---

packages/topgrade-bin/topgrade-bin.pacscript

https://github.com/r-darwish/topgrade was archived
https://github.com/topgrade-rs/topgrade is the community effort to keep maintaining the project
In this MR, I rename the executable from topgrade-rs to topgrade
An other option would be to create a separate new package topgrade-rs-bin
Yet an other option is to change the name of this package to topgrade-rs-bin and change it in the packagelist but I don't know how well will pacstall manage this for users

upd(topgrade-bin): `9.0.1` -> `9.1.0`

---

packagelist
packages/libicu71-deb/libicu71-deb

As a dependency for fsearch-deb in jammy https://github.com/pacstall/pacstall-programs/pull/1712

add: `libicu71-deb`

---

packages/rhino-linux-xfce4-config/rhino-linux-xfce4-config.pacscript

This issue is being fixed upstream so this isn't need and it was failing (?) for some reason despite it being forced.

fix(rhino-linux-xfce4-config): don't remove extra files

---

packages/ani-cli-bin/ani-cli-bin.pacscript

What the hell guys?
Ani-cli isn't a binary and very much relies on it's runtime dependencies

fix(ani-cli-bin): add runtime dependencies

---

packages/freetube-deb/freetube-deb.pacscript

Added Repology info for easy update, and updated it to latest beta 0.18.0

fix & upd(freetube-deb): `0.17.1` -> `0.18.0`

---

packages/discord-canary/discord-canary.pacscript

Temporarily restricts repology information to the AUR to mitigate https://github.com/pacstall/website/issues/228

fix(discord-canary): Temporarily restrict repology to AUR

---

packagelist
packages/muse-hub-deb/muse-hub-deb.pacscript

First, thank you for this great tool !
I'd like to add MuseScore (a great free music edition tool) to pacstall as it is only present as 2.x and 3.4.x in apt, where last version is 4.X with great improvements.
`muse-hub` would be an optional dependency of MuseScore.
Please note that I added `icu-devtools` as a dependency because `muse-hub` seems to need `libicu`.
However, this library is only provided along with a version number in apt, and that depends on the ubuntu/debian version.
I noticed that there is a `libicu71-deb` package in pacstall. Would it be better to use it ?
Moreover, I'd like some help with the `removescript`: despite the `rm -rf` I did in it, the directory `/srv/muse-hub` still exists after uninstall (I tried using both `apt remove` and `pacstall -R`)
Thanks!

add: `muse-hub`

---

packagelist
packages/libssl1.1-deb/libssl1.1-deb.pacscript

Still on my MusesScore stuff, `libssl.so.1.1` is required to run but not available on ubuntu since 22.04.
This pacscript provides `libssl1.1` from ubuntu 20.04, and does not seem to collide with `libssl3` package from newer versions of ubuntu

add: `libssl1.1-deb`

---

packages/polybar/polybar.pacscript

I was getting the following error with the current pacsript implementation:
```
[+] INFO: Extracting polybar-3.6.3.tar.gz
[+] INFO: Running functions
[>] Running prepare
[>] Running build
CMake Error: The source directory "/tmp/pacstall" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
[!] ERROR: Could not build polybar properly
dpkg: warning: ignoring request to remove polybar which isn't installed
[+] INFO: Cleaning up
```
I fixed it and successfully installed the package with my proposed changes.
Please let me know if those changes are okay or need improvements.

fix(polybar): fix build logic

---

packages/latte-dock-git/latte-dock-git.pacscript

Add dependency on plasma-workspace and plasma-desktop
If installed in a DE different from Plasma, and build_depends removed after installation, latte-dock will fail to run.

fix: latte-dock-git dependencies

---

packages/wezterm-bin/wezterm-bin.pacscript

Updated WezTerm to the latest version (Hopefully everything is correct)

upd(wezterm-bin): `20230326-111934-3666303c` -> `20230408-112425-69ae8472`

---

.github/workflows/tests.yml

If a package is removed by `replace` for example, the remove step will fail because it already has been removed. This PR makes the CI remove based on actually installed packages.

fix(ci): remove based on installed packages

---

packages/vscode-insiders-deb/vscode-insiders-deb.pacscript

I needed to duplicate the variable related to the version, because, based on the [repology: vscode](https://repology.org/project/vscode/versions), the `insiders` versions of vscode, have the `-insiders` suffix, which is not compatible with the **.debs** download url.

fix: `vscode-insiders-deb`

---

packagelist
packages/nyxt-deb/nyxt-deb.pacscript

The deb version of nyxt was removed in favor of a self contained package with the [`3.0.0` version](https://github.com/atlas-engineer/nyxt/releases/tag/3.0.0) which is very thick.

rm: `nyxt-deb`

---

packages/rhino-core/rhino-core.pacscript
packages/rhino-pine-core/rhino-pine-core.pacscript
packages/rhino-server-core/rhino-server-core.pacscript

Notable changes:
`core` and `pine-core` now have rhino-system as a pacdep
`pine-core` now has mobile-usb-networking as a pacdep

upd(rhino{-pine,-server,}-core): `2023.1-beta5-2` -> `2023.1-beta6-0`

---

packages/smplayer-deb/smplayer-deb.pacscript

This also fixes the variable on the package, and marks it correctly as orphaned.

upd(smplayer-deb): `22.7.0` -> `23.6.0`

---

packages/megasync-deb/megasync-deb.pacscript

Only these distos are supported:
- Ubuntu 22.04
- Ubuntu 23.04
- Debian 11
- Debian 12

upd(megasync-deb): `4.9.4-3.1` -> `4.9.5-1.1`

---

packagelist
packages/mint-themes/mint-themes.pacscript

Just because its hard to get as a package on Debian and Ubuntu when the Mint Y icons exist on both.

add: `mint-themes`

---

packages/cmake-data-deb/cmake-data-deb.pacscript

This reverts commit acae0cfb8970aab48c5ae6fbfc0867983a7e78f7.
The update I did to cmake-data-deb was to update cmake-deb but cmake-deb 3.27.0 will not install on ubuntu jammy, kinetic, and lunar so I would like to revert that commit to unbreak cmake-deb until I find a better solution
Sorry about that

Revert "upd(cmake-data-deb): `3.25.1` -> `3.27.0` (#4149)"

---

packages/rhino-pine-core/rhino-pine-core.pacscript

This does NOT need a pkgrel bump as it will not have an effect on any current users whatsoever. This is purely for the pipeline creating 2023.2+

fix(rhino-pine-core): modem-start deprecated

---

packagelist
packages/zoxide-deb/zoxide-deb.pacscript

Despite zoxide being in the official Debian repositories, the version is very old. Please approve the pull request so that the open-source community can use the current version.

add: `zoxide-deb`

---

packages/megasync-deb/megasync-deb.pacscript

Only compatible with:
Ubuntu 22.04 and derivatives
Ubuntu 23.04 and derivatives
Debian 11
Debian 12

upd(megasync-deb): `4.9.5-1.1` -> `4.9.6-1.1`

---

packages/lutris-deb/lutris-deb.pacscript

Missing dependency from github .deb (useless if using OBS repository, bug reported to lutris team too)
Permit the header banner to be visible on lutris

fix(lutris-deb): add `depends`

---

packages/rhino-pkg-git/rhino-pkg-git.pacscript

Update rhino-pkg-git to v0.1.2 when https://github.com/rhino-linux/rhino-pkg/issues/32 is closed.

upd(rhino-pkg-git): `0.1.1` -> `0.1.2`

---

packages/discord-canary/discord-canary.pacscript

Also removes repology AUR pinning since that issue appears to be fixed now.

upd(discord-canary): `0.0.170` -> `0.0.171`

---

packages/wezterm-app/wezterm-app.pacscript

Updated Package
Fixed removal of default config to actually point to config 
Fixed method for fetching the icon as it was giving me weird resutls - was downloading an unopenable file.
One thing - why is there a .desktop file included in the `wezterm-app` dir - there is a line that then downloads and installs one - maybe im missing something.

upd(wezterm-app): `20230408-112425-69ae8472` -> `20230712-072601-f4abf8fd` Update Package 

---

packages/pacstall-gui-git/pacstall-gui-git.pacscript

In my script, the location of `settings.sh` has changed so I have updated this to reflect that.

fix(pacstall-gui-git): Change `settings.sh` install location

---

packages/helix/helix.pacscript

https://github.com/helix-editor/helix/releases/tag/23.10 released on October 25, 2023

upd(helix): `23.05` -> `23.10`

---

packages/pacstall-gui-git/pacstall-gui-git.pacscript

yad is available on Ubuntu and Debian. Compiling from source breaks the native one with bad version (yad 13 / yad 0.40)
Tested OK 30/10/2023 Debian 12/Ubuntu 22.04

fix(pacstall-gui-git): change pacdepends="yad" to depends="yad"

---

packages/brave-browser-deb/brave-browser-deb.pacscript

Upgrading to https://github.com/brave/brave-browser/releases/latest

upd(brave-browser-deb): `1.59.117` -> `1.59.124`

---

packages/zettlr-deb/zettlr-deb.pacscript

upd(zettlr-deb): `2.3.0` -> `3.0.2`

---

packages/meson-focal-deb/meson-focal-deb.pacscript

mfw the array was made with this package hyper-specifically in mind but I never updated it

fix(meson-focal-deb): use `compatible` array

---

packagelist
packages/watchexec/watchexec.pacscript

Add an initial version of watchexec package. The project supports more architectures and provides completion for more shells, I only added the ones I use and can easily test.

add: `watchexec`

---

packagelist
packages/watchexec-bin/watchexec-bin.pacscript

Given the package is actually binary

fix(watchexec): update the name to `watchexec-bin`

---

packagelist
packages/exercism-cli-bin/exercism-cli-bin.pacscript
packages/exercism-cli/exercism-cli.pacscript

Tested both on an x86_64 laptop and on an amd64 Pi 4.

add: `exercism-cli-bin`

---

packages/plexmediaserver-deb/plexmediaserver-deb.pacscript

Parameterize the download URL based on architecture

fix(plexmediaserver-deb): fix deb URL for arm64

---

packages/discord/discord.pacscript

Updating Discord Version from 0.0.36 to 0.0.39
TESTED: Ubuntu 22.04

upd(discord): `0.0.36` -> `0.0.39`

---

packages/hakuneko-deb/hakuneko-deb.pacscript

Debian/Ubuntu don't support that architecture

fix(hakuneko-deb): `dpkg` does not recognize `armv7l`

---

packages/fastfetch-git/fastfetch-git.pacscript

pkgver: latest version
makedepends: add libmagickcore-dev, libmagick++-dev
move libpci-dev from optdepends to makedepends
add kitty to optdepends (used to display png)

upd(fastfetch-git): `2.2.3` -> `2.6.3`

---

packages/fastfetch-git/fastfetch-git.pacscript

not critical: 
libmagickcore-dev was called twice as makedepends

fix(fastfetch-git): deleted libmagickcore-dev dependency (called twice)

---

packages/stockfish-git/stockfish-git.pacscript

I missed the key step of stripping the exectuable to make it smaller and faster, as well as using profile-build to do something good. This has been tested on my jetson xavier and jetson nano, so it will probably work. Thank y'all!

fix(stockfish-git): improve build sequence

---

packages/megasync-deb/megasync-deb.pacscript

Only compatible with:
- Ubuntu 22.04 and derivatives
- Ubuntu 23.04 and derivatives
- Ubuntu 23.10 and derivatives
- Debian 11
- Debian 12

upd(megasync-deb): `4.9.6-1.1` -> `4.11.0-3.1`

---

packages/glow-deb/glow-deb.pacscript

Can't install `glow-deb` with `pacstall -I glow-deb` due to `[!] ERROR: 'arch64' is not a valid architecture`.

fix(glow-deb): fix arch64 is not a valid architecture

---

packages/oil/oil.pacscript

https://www.oilshell.org/ is still unstable and making changes, so it's good to be able to follow the latest version to keep up.
Not sure of etiquette here - @wizard-28 is marked is maintainer but doesn't seem to have been around for a bit? Will mark this as a draft for a while in the hope of getting some feedback on what's best to do.
I've deployed this locally and only needed one single-line patch to one of my scripts due to an apparent syntax change - to be expected as this is explicitly an unstable package. Other than that, nothing has exploded, and upstream has a pretty heavy test suite anyway.

upd(oil): `0.17` -> `0.20`

---

packagelist
packages/nerd-fonts-fira-code/nerd-fonts-fira-code.pacscript

i tried to use a tar.xz file, but it wasnt working, is there a compatibility issue with that type of archive? for the moment, zip works.

add: `nerd-fonts-fira-code`

---

packages/megasync-deb/megasync-deb.pacscript

Supported distro version:
- Debian 11 & 12
- Ubuntu 22.04 & 23.10
This update drops the support for Ubuntu 23.04

upd(megasync-deb): `4.11.0-3.1` -> `4.12.2-2.1`

---

packages/discord-canary/discord-canary.pacscript
packages/discord/discord.pacscript

Also, move interaction with `pkgdir` out of `prepare()`, since that's highly discouraged in PKGBUILDs.

feat(discord,discord-canary): symlink executable to PATH

---

packages/an-anime-game-launcher-bin/an-anime-game-launcher-bin.pacscript

Everything should be correct and An Anime Game Launcher should now be able to update to version 3.9.5 with pacstall.

upd(an-anime-game-launcher-bin): `3.9.4` -> `3.9.5`

---

packagelist
packages/goverlay-bin/goverlay-bin.pacscript

- Original Package from Elsie19 changed to goverlay-bin
- Add replace for goverlay
- Still in QT5 version for now, not updated to latest version

add: `goverlay-bin`

---

.github/workflows/pac5-conv.yml

creates a temp CI that runs the 5.0.0 conversion script freshly on top of the latest changes to master, every time there is a push to master. 
Force pushes the converted changes to a branch `5.0.0-master` so that there is no rebasing. It will always just be the one commit on top of the latest commit to `master`; will not force push if the conversion fails.
Checks out from upstream link to ensure true master is always the one selected.
Only takes 10-15 seconds. See:
https://github.com/oklopfer/pacstall-programs/actions/runs/8463596105
https://github.com/oklopfer/pacstall-programs/commits/5.0.0-master/

ci(pac5-conv.yml): add temp `5.0.0` converter/branch

---

packages/megasync-deb/megasync-deb.pacscript

Supported distros:
- Debian 11 & 12
- Ubuntu and derivatives 22.04 & 23.10

upd(megasync-deb): `4.12.2-2.1` -> `5.2.0-2.1`

---

.github/workflows/tests.yml

needed for 5.0.0 (bwrap) to run properly
technically doesn't need to be merged till 5.0.0 is released

ci(tests.yml): run containers privileged

---

packages/fastfetch-git/fastfetch-git.pacscript

just a version number update really (the script always downloads the latest version, but it's quite confusing when doing a `pacstall -L` list and it still says `2.6.1`).

upd(fastfetch-git): `2.6.1` -> `2.9.1`

---

packages/chezmoi-deb/chezmoi-deb.pacscript

Just a simple update for Chezmoi. I updated it in my fork and wanted to share. Hope you don't mind @oklopfer :smile:. 
I have updated the checksum to match the one in checksums.txt from the Github Release 2.47.2 for Chezmoi. The signature on the checksums file has been verified against the `chezmoi_cosign.pub` key using Cosign.

upd(chezmoi-deb): `2.45.0` -> `2.47.2`

---

packages/qt6pas/qt6pas.pacscript

As qt5pas was libqt5pas-dev libqt5pas1
Changed to  libqt6pas-dev libqt6pas1

fix(qt6pas): change gives and add provides to match realname

---

packages/hamclock/.SRCINFO
packages/hamclock/hamclock.pacscript

I've updated the package to current release from https://clearskyinstitute.com/ham/HamClock/

upd(hamclock): `3.10` -> `4.0.0`

---

.pre-commit-config.yaml
.shellcheckrc
packages/docker-bin/docker-bin.pacscript

Rationale: people constantly get confused when running shellcheck manually. This makes those invocations consistent with the pre-commit hook (which the args can be removed from now). Also suppresses redundant LSP warnings.
3 of the 4 codes I re-enabled triggered no warnings when run on all files, the fourth - only for one file, which I fixed.

feat: add .shellcheckrc, specify shell=bash, re-enable codes which are safe to enable

---

packages/jellyfin-media-player-deb/.SRCINFO
packages/jellyfin-media-player-deb/jellyfin-media-player-deb.pacscript

This build REQUIRES Jellyfin 10.9.1 or later to work. You will get a blank home screen if you don't use a new enough server version.
For more info go [here](https://github.com/jellyfin/jellyfin-media-player/releases/tag/v1.10.1).

upd(jellyfin-media-player-deb): `1.9.1` -> `1.10.1`

---

scripts/srcinfo.sh

create the output inside of awk and trim off the extra space before printing

ci(srcinfo.sh): fix ghost distro

---

.pre-commit-config.yaml

This fixes a ordering issue caused by locale-specific issues in packagelist sorting.
LC_ALL=C keeps a consistent sort, whether using en_US, en_CA, or any other locale by always defining it during the pre-commit run.

ci(.pre-commit-config.yaml): locale issues with pre-commit-config

---

packages/hakuneko-deb/.SRCINFO
packages/lsd-deb/.SRCINFO
scripts/srcinfo.sh

now I have to go add this to pacstall + pacup too :(

ci(srcinfo.sh): fix AARCH + CARCH replace

---

packages/the-honkers-railway-launcher-bin/.SRCINFO
packages/the-honkers-railway-launcher-bin/the-honkers-railway-launcher-bin.pacscript
srclist

- Updated to `1.7.1`
- Removed `xdelta3` as dependency
- Removed `cd "${_archive}"`
Had been tested locally, confirm working (at least on my side).

upd(the-honkers-railway-launcher-bin): `1.6.1` -> `1.7.1`

---

packages/opensnitch-ui-deb/.SRCINFO
packages/opensnitch-ui-deb/opensnitch-ui-deb.pacscript
srclist

someone emailed about `qt-material` not existing in the mint repos, I checked and I don't think opensnitch-ui needs this to run

fix(opensnitch-ui-deb): remove qt-material dependency

---

packagelist
packages/libcs50-git/.SRCINFO
packages/libcs50-git/libcs50-git.pacscript
srclist

Add new package libcs50-git
This is my first time to do any contribution to any project.

add: `libcs50-git`

---

packagelist
packages/ffnvcodec-headers/.SRCINFO
packages/ffnvcodec-headers/ffnvcodec-headers.pacscript
srclist

First contribution so let me know if something looks wrong

add: `ffnvcodec-headers`

---

packages/zen-browser-generic-bin/zen-browser-generic-bin.pacscript
packages/zen-browser-specific-bin/zen-browser-specific-bin.pacscript

Use the same bin path as AUR and COPR. Add update policy, as it's managed by pacstall.

fix(zen-browser-{generic,specific}-bin): bin and policies

---

packages/zed-editor-preview-bin/.SRCINFO
packages/zed-editor-preview-bin/zed-editor-preview-bin.pacscript
packages/zed-editor-stable-bin/.SRCINFO
packages/zed-editor-stable-bin/zed-editor-stable-bin.pacscript
srclist

As requested here: https://github.com/zed-industries/zed/pull/18576#issuecomment-2385724834
Sorry! I missed this file when inspecting archives to create packages.

upd(zed-editor-{stable,preview}-bin): add missing licenses files, bump pkgrel

---

packagelist
packages/orchis-kde/.SRCINFO
packages/orchis-kde/orchis-kde.pacscript
srclist

This package [exists](https://packages.ubuntu.com/oracular/orchis-kde) in Ubuntu, but only for noble and oracular and is outdated. A theme repo doesn't have tags or releases, although new commits appear very rarely, so each new commit can be considered a new release. Ubuntu package uses `YYYY-MM-DD` version format, so did I.

add: `orchis-kde`

---

packagelist
packages/ollama-bin/.SRCINFO
packages/ollama-bin/ollama-bin.pacscript
packages/ollama-bin/ollama.service
srclist

add: `ollama-bin`

---

packagelist
packages/dremio-bin/.SRCINFO
packages/dremio-bin/dremio-bin.pacscript
srclist

:)
Since there is no official way to install this open source software in Ubuntu, I thought I could contribute.
The script is mostly inspired from the docker and android studio ones.

add: `dremio-bin`

---

packages/bazecor-app/bazecor-app.pacscript
packages/joplin-desktop-app/joplin-desktop-app.pacscript
packages/krita-app/krita-app.pacscript
packages/librewolf-app/librewolf-app.pacscript
packages/lunarclient-app/lunarclient-app.pacscript
packages/minecraft-pi-reborn-app/.SRCINFO
packages/minecraft-pi-reborn-app/minecraft-pi-reborn-app.pacscript
packages/mymonero-app/mymonero-app.pacscript
packages/neovim-app/neovim-app.pacscript
packages/rpcs3-app/rpcs3-app.pacscript
packages/suyu-app/suyu-app.pacscript
packages/texstudio-app/texstudio-app.pacscript
packages/tutanota-app/tutanota-app.pacscript
packages/upscayl-app/upscayl-app.pacscript
packages/walc-app/walc-app.pacscript
srclist

`_archive` will never be enterable because it is an appimage, so it is unneeded
just say `cd "${srcdir}"` for clarity sake, though this is also redundant as each functions starts in `srcdir`

ref(*): drop `_archive` usage from all `-app` packages

---

packages/ungoogled-chromium-deb/.SRCINFO
packages/ungoogled-chromium-deb/ungoogled-chromium-deb.pacscript
srclist

Updates for `ungoogled-chromium-deb` from `130.0.6723.91-stable1` into `131.0.6778.204-stable1` (Also fixes the 404 issue in previous pacscripts).

upd(ungoogled-chromium-deb): `130.0.6723.91-stable1` -> `131.0.6778.204-stable1`

---

packages/helix/.SRCINFO
packages/helix/helix.pacscript
srclist

This somewhat aligns the behavior with other packaging of Helix,
such as Snap and Archlinux.

fix(helix): Also make a symlink to the actual package name

---

scripts/srcinfo.sh

See https://github.com/pacstall/pacstall/pull/1308

ci(srcinfo.sh): reduce overhead usage, repair search

---

packages/asdf-vm/.SRCINFO
packages/asdf-vm/asdf-vm.pacscript
srclist

Update `asdf-vm` to latest version `0.15.0`

upd(asdf-vm): `0.14.1` -> `0.15.0`

---

packages/ungoogled-chromium-bin/.SRCINFO
packages/ungoogled-chromium-bin/ungoogled-chromium-bin.pacscript
srclist

New fresh updates for `ungoogled-chromium-bin`.

upd(ungoogled-chromium-bin): `131.0.6778.139-1` -> `132.0.6834.110-1`

---

packages/noisetorch-bin/.SRCINFO
packages/noisetorch-bin/noisetorch-bin.pacscript
srclist

fix(noisetorch-bin): fix source

---

packages/vscodium-bin/.SRCINFO
packages/vscodium-bin/vscodium-bin.pacscript
srclist

Just minor fixes for second sources. Reasons are in titles.

fix(vscodium-bin): fix the sums on second sources due dynamically downloads

---

packages/hamclock-big/.SRCINFO
packages/hamclock-big/hamclock-big.pacscript
packages/hamclock-bigger/.SRCINFO
packages/hamclock-bigger/hamclock-bigger.pacscript
packages/hamclock-huge/.SRCINFO
packages/hamclock-huge/hamclock-huge.pacscript
packages/hamclock/.SRCINFO
packages/hamclock/hamclock.pacscript
srclist

Update hamclock to 4.13
Update pacscripts for hamclock code restructure so disabled update message and PAC version suffix continue to display.

upd(hamclock{,-big,-bigger,-huge}): `4.11` -> `4.13`

---

packages/eza-git/eza-git.pacscript

Currently installation fails with error message: `install: cannot stat 'LICENCE': No such file or directory`

fix(eza-git): fix installing license

---

packagelist
packages/lm-studio-app/.SRCINFO
packages/lm-studio-app/lm-studio-app.pacscript
srclist

Adds lm-studio for x86 (I presume they meant x86_64) via the official AppImage. Tested successfully on an x86_64 CPU.
Since the AppImage does not include a working Icon, this script currently also retrieves the website's favicon and installs it to the appropriate location.

add: `lm-studio-app`

---

packagelist
packages/rhinu-pkg-git/.SRCINFO
packages/rhinu-pkg-git/rhinu-pkg-git.pacscript
srclist

@ajstrongdev and I want this to be a separate package that is used in `rhino-stampede-dev` first, since we want to ensure there are no critical issues post-review.

add: `rhinu-pkg-git`

---

packages/insomnia-deb/.SRCINFO
packages/insomnia-deb/insomnia-deb.pacscript
srclist

It seems that starting with some version `8.*` - or `2023.*` - a versioning change was done. That unfortunately means that apt will reject updating an existing installation - although in my case running the installation cmd twice did work, so I'm assuming it did uninstall the old package before complaining about the version downgrade (after all, 11 << 2023).
I'm not aware of a pacscript definition that would tell apt to ignore versioning...

upd(insomnia-deb): `2023.4.0` -> `11.1.0`

---

packages/vscodium-deb/.SRCINFO
packages/vscodium-deb/vscodium-deb.pacscript
srclist

As v1.99 is quite a few months old I took the liberty to update the package.

upd(vscodium-deb): `1.99.32846` -> `1.101.03933`

---

packagelist
packages/libndi4-deb/.SRCINFO
packages/libndi4-deb/libndi4-deb.pacscript
packages/obs-ndi-deb/.SRCINFO
packages/obs-ndi-deb/obs-ndi-deb.pacscript
srclist

This PR removes 
- libndi4
- obs-ndi
Reasons to do so:
- LibNDI is 6.2.0 and not provided as a package by publisher. v4 is extremely old.
- obs-ndi is no longer a valid package, has been replaced by [DistroAV](https://github.com/DistroAV/DistroAV/)
I do not plan to test theses changes as they are removal only.
libndi4 was only a requirement for obs-ndi
Thanks

rm: `libndi4`, `obs-ndi`

---

packages/digikam-app/.SRCINFO
packages/digikam-app/digikam-app.pacscript
srclist

Not found in repology, updated via -c flag.

upd(digikam-app): `8.6.0` -> `8.7.0`

---

packages/hamclock-big/.SRCINFO
packages/hamclock-big/hamclock-big.pacscript
packages/hamclock-bigger/.SRCINFO
packages/hamclock-bigger/hamclock-bigger.pacscript
packages/hamclock-huge/.SRCINFO
packages/hamclock-huge/hamclock-huge.pacscript
packages/hamclock/.SRCINFO
packages/hamclock/hamclock.pacscript
srclist

Updated to 4.20
Removed patches to stop automatic updates, software maintainer added compile time flag to disable updates.

upd(hamclock{,-big,-bigger,-huge}): `4.19` -> `4.20`

---

packages/hamclock-big/hamclock-big.pacscript
packages/hamclock-bigger/hamclock-bigger.pacscript
packages/hamclock-huge/hamclock-huge.pacscript
packages/hamclock/hamclock.pacscript

Fix a packaging error using wrong desktop shortcut from upstream tarball points to invalid path.

upd(hamclock{,-big,-bigger,-huge}): Fix pacscripts to use correct hamclock.desktop file

---

packages/bitwarden-cli-bin/.SRCINFO
packages/bitwarden-cli-bin/bitwarden-cli-bin.pacscript
srclist

Updated bitwarden-cli, and also added installation to the zsh completion (it does not provide completion for other shells).

upd(bitwarden-cli-bin): `2025.7.0` -> `2025.9.0`
